name: Python-build
on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: CheckoutCode
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.9'

      - name: Instaling dependencies
        run: |
           python3 -m pip install --upgrade pip
           touch requirements.txt
           echo "pytest==7.4.0" >> requirements.txt
           echo "flask==2.3.3" >> requirements.txt
           echo "requests==2.31.0 >> requirements.txt"
           cat requirements.txt
           pip install -r requirements.txt
      - name: Python version
        run: | 
           env | grep python && echo $PATH
                



    
  
