name: Python-build
on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: CheckoutCode
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: ['3.9', '3.10']

      - name: Install dependecies
        run: |
        python --version

      - name: Run tests
        run: |
        pytest
    
  
